In [1]:
import numpy as np

In [2]:
# Creating a vector as row
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [3]:
# Creating a vector as column
vector_column = np.array([[1],
                         [2],
                         [3]])
vector_column

array([[1],
       [2],
       [3]])

In [4]:
# Creating a Matrix
matrix = np.array([[1, 2],
                  [1, 2],
                  [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
# Creating a Sparse Matric
from scipy import sparse
matrix = np.array([[1,0],
                   [0, 0],
                    [0, 3],
                    [0, 1]])

sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

  (0, 0)	1
  (2, 1)	3
  (3, 1)	1


In [10]:
# Apply Operations to Elements
matrix = np.array([[1, 2], 
                  [2, 4],
                  [5, 10]])
add_100 = lambda x: x + 100
vectorized_add_100 = np.vectorize(add_100) # This function let's a function apply to every element of an array
vectorized_add_100(matrix)

array([[101, 102],
       [102, 104],
       [105, 110]])

In [11]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
print('Max along row: {}'.format(np.max(matrix, axis=1)))
print('Min along row: {}'.format(np.min(matrix, axis=1)))
print('Max along column: {}'.format(np.max(matrix, axis=0)))
print('Min along column: {}'.format(np.min(matrix, axis=0)))

Max along row: [3 6 9]
Min along row: [1 4 7]
Max along column: [7 8 9]
Min along column: [1 2 3]


In [12]:
# Calculating Average, Variance, Std. Deviation
matrix = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
print('Mean in total: {}'.format(np.mean(matrix)))
print('Variance in total: {}'.format(np.var(matrix)))
print('Std. Deviation in total: {}'.format(np.std(matrix)))

print('*'*63)

print('Mean along columns: {}'.format(np.mean(matrix, axis=0)))

Mean in total: 5.0
Variance in total: 6.666666666666667
Std. Deviation in total: 2.581988897471611
***************************************************************
Mean along columns: [4. 5. 6.]


In [13]:
# Finding the Rank of a Matrix
matrix = np.array([[1, 1, 2],
                  [2, 0, 4],
                  [3, 2, 6]])
np.linalg.matrix_rank(matrix)

2

In [14]:
# Calculating the Determinant of a Matrix
matrix = np.array([[1, 1, 2],
                  [2, 0, 4],
                  [3, 2, 6]])
np.linalg.det(matrix)

0.0

In [16]:
# Getting the Diagonal of a Matrix
matrix = np.array([[1, 1, 2],
                  [2, 0, 4],
                  [3, 2, 6]])
print('Main Diagonal {}'.format(matrix.diagonal()))
print('Diagonal one above Main Diagonal {}'.format(matrix.diagonal(offset=1)))
print('Diagonal one below Main Diagonal {}'.format(matrix.diagonal(offset=-1)))

Main Diagonal [1 0 6]
Diagonal one above Main Diagonal [1 4]
Diagonal one below Main Diagonal [2 2]


In [17]:
# Calculating the Trace of a Matrix
matrix = np.array([[1, 1, 2],
                  [2, 0, 4],
                  [3, 2, 6]])
matrix.trace()

7

In [18]:
# Finding the Eigen Value and Vector of a Matrix
matrix = np.array([[1, 1, 2],
                  [2, 0, 4],
                  [3, 2, 6]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[ 8.21699057e+00  7.92907542e-18 -1.21699057e+00]
[[-2.95513359e-01 -8.94427191e-01  3.03428475e-01]
 [-4.75331844e-01 -4.69171996e-16 -9.43205983e-01]
 [-8.28692640e-01  4.47213595e-01  1.35253958e-01]]


In [19]:
# Calculating the dot product
vector_a = np.array([1, 2, 3])
vector_b = np.array([2, 4, 6])
np.dot(vector_a, vector_b)

28

In [20]:
# Inverting a Matrix
matrix = np.array([[1, 4],
                  [4, 2]])
np.linalg.inv(matrix)

array([[-0.14285714,  0.28571429],
       [ 0.28571429, -0.07142857]])